baseurl = "http://josa42.github.io/"
languageCode = "en-us"
theme = "simple"

title = "Josa Gesell"

[params]
subtitle = "My Blog"
mainSections = ["post", "photo"]

[ permalinks ]
  post = "/:year-:month-:day-:title"
  page = "/:title"

[ menu ]
  [[ menu.main ]]
    name = "Posts"
    url = "/"
    weight = -1