name = "Simple"
license = ""
licenselink = ""
description = ""
homepage = ""
tags = ["clean", "simple"]
features = ["highlightjs", "Blog only"]
min_version = 0.16

[author]
  name = "Josa Gesell <josa@gesell.me"

[original]
  author =  "Lasse Borly <contact@lasseborly.dk"
  homepage = "https://lasseborly.dk/"
  repo = "https://github.com/lasseborly/anybodyhome/"
